### ISSUE TITLE
Switch clock from real-time mode to single-step mode while simulation is running?

### ISSUE THREAD

**Issue by prlaba** [LandryNorris/DigitalLogicSimulator#1]
Not an issue per-se, more a question.  I'm a longtime user of Logisim and Logisim-Evolution and am still getting used to Digital.

Digital only allows a component's attributes to be changed when the simulator is stopped.  That makes great sense except for the clock component's _Start in real time_ attribute.

I often want to switch from "real-time" clock mode to "single-step" clock mode while the simulator is running.  Stopping and re-starting the simulator doesn't do what I need as my circuit is re-initialized as soon as the simulation is stopped.

Three solutions I can think of: 1) Add Pause and Resume buttons (pressing Pause stops the simulation but maintains state; pressing Resume resumes from the same state); 2) Allow a Clock component's _Start in real time_ attribute to be changed while the simulator is running;  3) Add a Wall Clock icon/button next to the Start and Stop icon/buttons; toggling that button would switch the clock from real-time to single-step mode and vice-versa while the simulation is running.

Are there other ways to do what I want, without any changes to Digital itself?

**Comment by LandryNorris** [comment]
I think you're looking at the wrong GitHub project. This is a project I started in College, then stopped working on for a couple years, due to lack of time. This project is still early development and has none of the features or UI you mentioned. You may be looking for [this](https://github.com/hneemann/Digital)?
